name: SafeHorses
main: com.michaelelin.SafeHorses.SafeHorsesPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: true
authors: [Dumbo52]
permissions:
  safehorses.*:
    description: Gives access to all SafeHorses commands/options
    children:
      safehorses.spawn: true
      safehorses.info: true
      safehorses.appearance: true
      safehorses.rename: true
      safehorses.neigh: true
      safehorses.other.*: true
  safehorses.spawn:
    description: Allows players to spawn their own horses.
  safehorses.info:
    description: Gives information about the owner of someone else's horse when right-clicking it.
  safehorses.appearance:
    description: Allows players to change their horse's appearance.
  safehorses.rename:
    description: Allows players to rename their horses.
  safehorses.neigh:
    description: Allows players to make their horses neigh.
  safehorses.other.*:
    description: Allows players to modify other players' horses.
    children:
      safehorses.other.spawn: true
      safehorses.other.despawn: true
      safehorses.other.clear: true
  safehorses.other.spawn:
    description: Allows players to spawn other players' horses.
  safehorses.other.despawn:
    description: Allows players to despawn other players' horses.
  safehorses.other.clear:
    description: Allows players to clear other players' horse data.
commands:
  horse:
    description: SafeHorses commands
    usage: /<command> help